name: .NET Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read
  checks: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0" # Specify the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test_results.trx"

      # get a ssh session at this point in the workflow
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Pack
        run: dotnet pack --no-build --output nupkgs

      - name: Publish
        run: dotnet nuget push AppForActions/**/*.nupkg -k ${{secrets.NEXUS_API_KEY}} -s http://repos.ad.bedegaming.com:8081/repository/nuget-components/


        
