name: .NET Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0" # Specify the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test_results.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
            name: test-results
            path: '**/test_results.trx'

      - name: Publish Test Results
        uses: dorny/test-reporter@v1  # seems widely used
        if: always() # even if the previous step failed
        with:
            name: 'NUnit Test Results'
            path: '**/test_results.trx'
            reporter: 'dotnet-trx'